name: Ubuntu use ccache

on: 
  push:
    branches: [ "ccache" ]

env:
  BUILD_TYPE: Release
  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Install ccache
      run: sudo apt-get install -y ccache

    - name: CMake ccache Setup
      shell: cmake -P {0}
      run: |
        set(ENV{CCACHE_COMPRESS} "true")
        set(ENV{CCACHE_COMPRESSLEVEL} "6")
        set(ENV{CCACHE_MAXSIZE} "600M")

# file(TO_CMAKE_PATH "$ENV{GITHUB_WORKSPACE}" ccache_basedir)
# set(ENV{CCACHE_BASEDIR} "${ccache_basedir}")
# set(ENV{CCACHE_DIR} "${ccache_basedir}/.ccache")

    - name: Restore cached ccache
      id: cache-ccache-restore
      uses: actions/cache/restore@v3
      with:
        path: .ccache
        key: ${{ runner.os }}-ccache

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build Application
      run: cmake --build ${{ github.workspace }} --config ${{ env.BUILD_TYPE }} --target dndmanager

    - name: print ccache path
      id: ccache-path
      run: |
        ccache -p | grep cache_dir | awk '{ print $4 }'

    - name: ccache statistics
      run: ccache -s

    - name: test step output
      run: |
        echo ${{ steps.ccache-path.outputs }}

    - name: Save ccache
      id: cache-ccache-save
      uses: actions/cache/save@v3
      with:
        path: .ccache
        key: ${{ steps.cache-ccache-restore.outputs.cache-primary-key }}
  