name: Ubuntu use ccache

on: 
  push:
    branches: [ "ccache" ]

env:
  BUILD_TYPE: Release
  DND_TARGET: dndmanager
  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Install ccache
      run: sudo apt-get install -y ccache

    - name: CMake ccache Setup
      shell: cmake -P {0}
      run: |
        set(ENV{CCACHE_COMPRESS} "true")
        set(ENV{CCACHE_COMPRESSLEVEL} "6")
        set(ENV{CCACHE_MAXSIZE} "600M")

    - name: determine ccache path
      id: ccache-path
      run: echo "path=$(ccache -p | grep cache_dir | awk '{ print $4 }')" >> $GITHUB_OUTPUT

    - name: Restore cached ccache
      id: cache-ccache-restore
      uses: actions/cache/restore@v3
      with:
        path: "${{ steps.ccache-path.outputs.path }}"
        key: ${{ runner.os }}-ccache-${{ env.DND_TARGET }}

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build Application
      run: cmake --build ${{ github.workspace }} --config ${{ env.BUILD_TYPE }} --target ${{ env.DND_TARGET }}

    - name: ccache statistics
      run: ccache -s

    - name: Save ccache
      id: cache-ccache-save
      uses: actions/cache/save@v3
      with:
        path: "${{ steps.ccache-path.outputs.path }}"
        key: ${{ steps.cache-ccache-restore.outputs.cache-primary-key }}
  