name: "Build and Run Unit Tests"

on:
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  UnitTesting:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build Unit Tests
      run: cmake --build ${{ github.workspace }} --config ${{env.BUILD_TYPE}} --target dndmanager_tests

    - name: Run Unit Tests
      working-directory: ${{ github.workspace }}
      run: ctest -C ${{ env.BUILD_TYPE }}