name: "WINDOWS: Build and Test"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "ccache" ]

env:
  BUILD_TYPE: Release
  DND_APP_TARGET: dndmanager
  DND_TEST_TARGET: dndmanager_tests
  CCACHE_DIR: "D:\\a\\AppData\\Local\\.cache/ccache"
  CCACHE_VERSION: 4.7.4
  

jobs:
  UnitTests:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - uses: lukka/get-cmake@latest

    - name: Download ccache
      run: Invoke-WebRequest -Uri https://github.com/ccache/ccache/releases/download/v${{ env.CCACHE_VERSION }}/ccache-${{ env.CCACHE_VERSION }}-windows-x86_64.zip  -OutFile '${{ github.workspace }}\ccache.zip'

    - name: Unzip ccache
      run: Expand-Archive -Path '${{ github.workspace }}\ccache.zip' -DestinationPath '${{ github.workspace }}'

    - name: CMake ccache Setup
      shell: cmake -P {0}
      run: |
        set(ENV{CCACHE_COMPRESS} "true")
        set(ENV{CCACHE_COMPRESSLEVEL} "6")
        set(ENV{CCACHE_MAXSIZE} "600M")
  
    - name: determine ccache path
      run: |
        Write-Output "hardcoded ccache path:"
        Write-Output "${{ env.CCACHE_DIR }}"
        Write-Output "real ccache path:"
        & ccache -p | Select-String cache_dir | ForEach-Object { $_.Line.Split(" ")[3] }

    - name: Restore cached ccache
      id: cache-ccache-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ runner.os }}-ccache-${{ env.DND_TEST_TARGET }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ env.DND_TEST_TARGET }}-
          ${{ runner.os }}-ccache-

    - name: Configure CMake
      run: cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -G "Ninja" -D CMAKE_MAKE_PROGRAM=ninja -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++

    - name: Build Unit Tests
      run: |
        $env:Path += ";${{ github.workspace }}\ccache-${{ env.CCACHE_VERSION }}-windows-x86_64"
        cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --target ${{ env.DND_TEST_TARGET }}

    - name: ccache statistics
      run: |
        $env:Path += ";${{ github.workspace }}\ccache-${{ env.CCACHE_VERSION }}-windows-x86_64"
        ccache -s

    - name: Save ccache
      id: cache-ccache-save
      uses: actions/cache/save@v3
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ runner.os }}-ccache-${{ env.DND_TEST_TARGET }}-${{ github.run_id }}

    - name: Find Unit Test
      working-directory: ${{ github.workspace }}/build
      shell: bash
      run: ls -lisah .

    - name: Run Unit Tests
      working-directory: ${{ github.workspace }}/build
      # run: ctest -C ${{ env.BUILD_TYPE }}
      shell: bash
      run: ./${{ env.DND_TEST_TARGET }}.exe


  App:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - uses: lukka/get-cmake@latest

    - name: Download ccache
      run: Invoke-WebRequest -Uri https://github.com/ccache/ccache/releases/download/v${{ env.CCACHE_VERSION }}/ccache-${{ env.CCACHE_VERSION }}-windows-x86_64.zip  -OutFile '${{ github.workspace }}\ccache.zip'

    - name: Unzip ccache
      run: Expand-Archive -Path '${{ github.workspace }}\ccache.zip' -DestinationPath '${{ github.workspace }}'

    - name: CMake ccache Setup
      shell: cmake -P {0}
      run: |
        set(ENV{CCACHE_COMPRESS} "true")
        set(ENV{CCACHE_COMPRESSLEVEL} "6")
        set(ENV{CCACHE_MAXSIZE} "600M")
  
    - name: determine ccache path
      run: |
        Write-Output "hardcoded ccache path:"
        Write-Output "${{ env.CCACHE_DIR }}"
        Write-Output "real ccache path:"
        & ccache -p | Select-String cache_dir | ForEach-Object { $_.Line.Split(" ")[3] }

    - name: Restore cached ccache
      id: cache-ccache-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ runner.os }}-ccache-${{ env.DND_APP_TARGET }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ env.DND_APP_TARGET }}-
          ${{ runner.os }}-ccache-

    - name: Configure CMake
      run: cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -G "Ninja" -D CMAKE_MAKE_PROGRAM=ninja -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++

    - name: Build Application
      run: |
        $env:Path += ";${{ github.workspace }}\ccache-${{ env.CCACHE_VERSION }}-windows-x86_64"
        cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --target ${{ env.DND_APP_TARGET }}

    - name: ccache statistics
      run: |
        $env:Path += ";${{ github.workspace }}\ccache-${{ env.CCACHE_VERSION }}-windows-x86_64"
        ccache -s

    - name: Save ccache
      id: cache-ccache-save
      uses: actions/cache/save@v3
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ runner.os }}-ccache-${{ env.DND_APP_TARGET }}-${{ github.run_id }}

    - name: Run Application with Imperial Data
      working-directory: ${{ github.workspace }}
      shell: bash
      run: ./build/${{ env.DND_APP_TARGET }}.exe -c example_campaign -d content_imperial

    - name: Run Application with Metric Data
      working-directory: ${{ github.workspace }}
      shell: bash
      run: ./build/${{ env.DND_APP_TARGET }}.exe -c example_campaign -d content_metric
  