name: "WINDOWS: Build and Run Integration Tests"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: ["ccache"]

env:
  BUILD_TYPE: Release
  DND_APP_TARGET: dndmanager
  DND_TEST_TARGET: dndmanager_tests
  CCACHE_DIR: "D:\\a\\AppData\\Local\\.cache/ccache"
  CCACHE_VERSION: 4.7.4

jobs:
  WindowsIntegrationTesting:
    runs-on: windows-latest
    
    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: lukka/get-cmake@latest

    - name: Download ccache
      run: Invoke-WebRequest -Uri https://github.com/ccache/ccache/releases/download/v${{ env.CCACHE_VERSION }}/ccache-${{ env.CCACHE_VERSION }}-windows-x86_64.zip  -OutFile '${{ github.workspace }}\ccache.zip'

    - name: Unzip ccache
      run: Expand-Archive -Path '${{ github.workspace }}\ccache.zip' -DestinationPath '${{ github.workspace }}'

    - name: CMake ccache Setup
      shell: cmake -P {0}
      run: |
        set(ENV{CCACHE_COMPRESS} "true")
        set(ENV{CCACHE_COMPRESSLEVEL} "6")
        set(ENV{CCACHE_MAXSIZE} "600M")

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build Application
      run: cmake --build ${{ github.workspace }} --config ${{ env.BUILD_TYPE }} --target dndmanager

    - name: Run Integration Test - Imperial
      working-directory: ${{ github.workspace }}
      run: ${{ github.workspace }}\\${{ env.BUILD_TYPE }}\\dndmanager.exe -c example_campaign -d ${{ github.workspace }}\\content_imperial

    - name: Run Integration Test - Metric
      working-directory: ${{ github.workspace }}
      run: ${{ github.workspace }}\\${{ env.BUILD_TYPE }}\\dndmanager.exe -c example_campaign -d ${{ github.workspace }}\\content_metric

    
